project:
  type: website
  pre-render: scripts/npn_download_prep.R
  output-dir: _site
  render:
    - "!template/*"
    - index.qmd
    - generated/*
    - semesters.qmd
  execute-dir: project

execute:
  freeze: auto

website:
  title: "UB Campus Phenology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Semester Data"
        href: semesters.qmd


format:
  html:
    theme: cosmo
    includes:
        after_body: include/after_body.html
